---

name: Test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/karras/archlinux-package-build:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Refresh and update packages
        run: |
          pacman -Syu --noconfirm

      # See https://github.com/docker/for-mac/issues/7331
      - name: Downgrade fakeroot to avoid freezes
        run: |
          pacman -U --noconfirm https://archive.archlinux.org/packages/f/fakeroot/fakeroot-1.34-1-x86_64.pkg.tar.zst

      - name: Assign ownership to builder user (hacky)
        run: |
          chown -R builder ./

      - name: Build packages
        run: |
          for PACKAGE in */PKGBUILD; do
            cd ${PACKAGE%%/*}
            sudo -u builder \
              makepkg --noconfirm --syncdeps --install
            cd ..
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./*/*.tar.zst
